Quiron.LojaVirtual.Web/Controllers/CarrinhoController.cs
using System.Configuration;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Quiron.LojaVirtual.Dominio.Entidades;
using Quiron.LojaVirtual.Dominio.Repositorio;
using Quiron.LojaVirtual.Web.Models;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class CarrinhoController : Controller
    {
        private ProdutosRepositorio _repositorio;

        public ViewResult Index(Carrinho carrinho, string returnUrl)
        {
            return View(new CarrinhoViewModel
            {
                Carrinho = carrinho,
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult Resumo(Carrinho carrinho)
        {
            return PartialView(carrinho);
        }

        public RedirectToRouteResult Adicionar(Carrinho carrinho, int produtoId, int quantidade, string returnUrl)
        {
            _repositorio = new ProdutosRepositorio();

            Produto produto = _repositorio.Produtos
                .FirstOrDefault(p => p.ProdutoId == produtoId);

            if(produto != null)
            {
                carrinho.AdicionarItem(produto, quantidade);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        //private Carrinho ObterCarrinho()
        //{
        //    Carrinho carrinho = (Carrinho)Session["Carrinho"];

        //    if (carrinho == null)
        //    {
        //        carrinho = new Carrinho();
        //        Session["Carrinho"] = carrinho;
        //    }

        //    return carrinho;
        //}

        public RedirectToRouteResult Remover(Carrinho carrinho, int produtoId, string returnUrl)
        {
            _repositorio = new ProdutosRepositorio();

            Produto produto = _repositorio.Produtos
                .FirstOrDefault(p => p.ProdutoId == produtoId);

            if(produto != null)
            {
                carrinho.RemoverItem(produto);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult FecharPedido()
        {
            return View(new Pedido());
        }

        [HttpPost]
        public ViewResult FecharPedido(Carrinho carrinho, Pedido pedido)
        {
            EmailConfiguracoes email = new EmailConfiguracoes
            {
                EscreverArquivo = bool.Parse(ConfigurationManager.AppSettings["Email.EscreverArquivo"] ?? "false")
            };

            EmailPedido emailPedido = new EmailPedido(email);

            if (!carrinho.ItensCarrinho.Any())
            {
                ModelState.AddModelError("", "Não foi possivel concluir o pedido, seu carrinho está vazio");
            }

            if (ModelState.IsValid)
            {
                emailPedido.ProcessarPedido(carrinho, pedido);
                carrinho.LimpparCarrinho();
                return View("PedidoConcluido");
            }
            else
            {
                return View(pedido);
            }
        }

        public ViewResult PedidoConcluido()
        {
            return View();
        }
    }
}

Quiron.LojaVirtual.Web/Controllers/CategoriaController.cs
using Quiron.LojaVirtual.Dominio.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class CategoriaController : Controller
    {
        private ProdutosRepositorio _repositorio;

        public PartialViewResult Menu(string categoria = null)
        {
            ViewBag.CategoriaSelecionada = categoria;

            _repositorio = new ProdutosRepositorio();

            IEnumerable<string> categorias = _repositorio.Produtos
                .Select(c => c.Categoria)
                .Distinct()
                .OrderBy(c => c);

            return PartialView(categorias);
        }
    }
}

Quiron.LojaVirtual.Web/Controllers/VitrineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Quiron.LojaVirtual.Dominio.Repositorio;
using Quiron.LojaVirtual.Web.Models;
using Quiron.LojaVirtual.Dominio.Entidades;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class VitrineController : Controller
    {
        private ProdutosRepositorio _repositorio;
        public int ProdutosPorPagina = 12;

        // GET: Produtos
        public ViewResult ListaProdutos(string categoria)
        {
            _repositorio = new ProdutosRepositorio();

            var model = new ProdutosViewModel();

            var rnd = new Random();

            if (categoria != null)
            {
                model.Produtos = _repositorio.Produtos
                    .Where(p => p.Categoria == categoria)
                    .OrderBy(x => rnd.Next()).ToList();
            }
            else
            {
                model.Produtos = _repositorio.Produtos
                    .OrderBy(x => rnd.Next())
                    .Take(ProdutosPorPagina).ToList();
            }



            //ProdutosViewModel model = new ProdutosViewModel
            //{
            //    Produtos = _repositorio.Produtos
            //        .Where(p => categoria == null || p.Categoria == categoria)
            //        .OrderBy(p => p.Descricao)
            //        .Skip((pagina - 1) * ProdutosPorPagina)
            //        .Take(ProdutosPorPagina),
            //    Paginacao = new Paginacao
            //    {
            //        PaginaAtual = pagina,
            //        ItensporPagina = ProdutosPorPagina,
            //        ItensTotal = categoria == null ? _repositorio.Produtos.Count() : _repositorio.Produtos.Count(e => e.Categoria == categoria)
            //    },
            //    CategoriaAtual = categoria
            //};

            return View(model);
        }

        public ViewResult Detalhes(int id)
        {
            _repositorio = new ProdutosRepositorio();

            Produto produto = _repositorio.ObterProduto(id);

            return View(produto);
        }

        [Route("Vitrine/ObterImagem/{produtoId}")]
        public FileContentResult ObterImagem(int produtoId)
        {
            _repositorio = new ProdutosRepositorio();

            Produto prod = _repositorio.Produtos
                .FirstOrDefault(p => p.ProdutoId == produtoId);

            if (prod != null)
            {
                return File(prod.Imagem, prod.ImagemMimeType);
            }

            return null;
        }
    }
}

Quiron.LojaVirtual.Web/Views/Shared/ProdutoDetalhes.cshtml
@model Quiron.LojaVirtual.Dominio.Entidades.Produto

<div class="well">
    @if(Model.Imagem != null)
    {
        <div class="row">
            <img class="img-thumbnail" width="120" height="120" src="@Url.Action("ObterImagem", "Vitrine", new { Model.ProdutoId })" />
        </div>
    }
</div>

<div class="row">
    <h4>
        @Html.ActionLink(Model.Nome, "Detalhes", "Vitrine", new { id = Model.ProdutoId, produto = Model.Nome.ToSeoUrl()}, new { @class = "deco-nome" })
        <br />
        <span class="pull-right label label-primary" >
            @Model.Preco.ToString("c")
        </span>
    </h4>
</div>





    @*
            <h3><strong>@Model.Nome</strong></h3>
            <h3><span class="pull-right label label-primary">@Model.Preco.ToString("c")</span></h3>
            @using (Html.BeginForm("Adicionar", "Carrinho"))
            {
                <div class="pull-right">
                    @Html.HiddenFor(x => x.ProdutoId)
                    @Html.Hidden("quantidade", 1)
                    @Html.Hidden("returnurl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="Comprar" />
                </div>
            }
            <h3><span class="lead">@Model.Descricao</span></h3>
    </div>
    *@

Quiron.LojaVirtual.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Quiron Loja Virtual</title>

    @*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/ErroEstilo.css" rel="stylesheet" />*@

    @Styles.Render("~/Content/css")


</head>
<body>
    
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">Quiron Loja Virtual - Seu Esporte é aqui</a>

        @Html.Action("Resumo", "Carrinho")

    </div>

    <div class="row panel">
        <div id="categorias" class="col-xs-3">
            @Html.Action("Menu","Categoria")
        </div>
        <div id="categorias" class="col-xs-8">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    @RenderSection("scripts", required: false )


</body>
</html>